### PR TITLE
133 PS review

### PR DESCRIPTION
**Pull request by astrofle**
Changes: 
- Where the user message about blanked integrations is issued.
- Adds more tests.

### CODE REVIEW

**Comment by astrofle** [comment]
Something that is quite puzzling is that:
```Python
import numpy as np
import dysh.util as util
from dysh.fits.gbtfitsload import GBTFITSLoad

testdata = util.get_project_testdata()
data_path = testdata  / "AGBT18B_354_03/AGBT18B_354_03.raw.vegas/AGBT18B_354_03.raw.vegas.A.fits"
sdf = GBTFITSLoad(data_path, verbose=False)

tp_scans = sdf.gettp(scan=[6,7], plnum=0)
np.all(sdf.gettp(scan=6, plnum=0).timeaverage().flux == tp_scans[0].timeaverage().flux)
```
Is not `True`!

**Comment by mpound** [comment]
The ScanBlocks in your example are not the same:

x=sdf.gettp(scan=6, plnum=0)
z=sdf.gettp(scan=[6,7], plnum=0)
print(len(x),len(z))
1 2

**Comment by astrofle** [comment]
> The ScanBlocks in your example are not the same:
> 
> x=sdf.gettp(scan=6, plnum=0) z=sdf.gettp(scan=[6,7], plnum=0) print(len(x),len(z)) 1 2

Bu isn't z[0] the same as x ?

**Comment by mpound** [comment]
Sorry, I misread the index in your example.  x and z are ScanBlocks. 

np.all(x[0]._data == z[0]._data)
True

But x[0] != z[0], so some metadata must be different.  
The issue seems to be (small) differences in Tsys weighting between Scan.timeaverage() and ScanBlock.timeaverage():

x.timeaverage().data - x[0].timeaverage().data
array([ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
       -7.4505806e-09,  0.0000000e+00,  0.0000000e+00])

np.all((x.timeaverage(weights=None).data - x[0].timeaverage(weights=None).data) == 0)
True

I tinkered with this earlier as there is a mode='old' and mode='new' (broken) for ScanBlock.timeaverage()

**Comment by astrofle** [comment]
> Sorry, I misread the index in your example. x and z are ScanBlocks.
> 
> np.all(x[0]._data == z[0]._data) True
> 
> But x[0] != z[0], so some metadata must be different. The issue seems to be (small) differences in Tsys weighting between Scan.timeaverage() and ScanBlock.timeaverage():
> 
> x.timeaverage().data - x[0].timeaverage().data array([ 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., -7.4505806e-09, 0.0000000e+00, 0.0000000e+00])
> 
> np.all((x.timeaverage(weights=None).data - x[0].timeaverage(weights=None).data) == 0) True
> 
> I tinkered with this earlier as there is a mode='old' and mode='new' (broken) for ScanBlock.timeaverage()

I see. Thanks for checking. 
No big issue though, the differences are small enough. We should open an issue so we can revisit this at some point.

**Comment by astrofle** [comment]
If the changes are acceptable, go ahead and merge. I'll approve the original PR after that.

**Review by mpound — APPROVED** [review]
I cleaned up the tests a bit, using your pytest.approx example.

**Pull request merged**
