### PR TITLE
270 readwrite interface for spectra scan scanblock

### PR DESCRIPTION
**Pull request by mpound**
This is a partial completion of the milestone.  This PR contains

1) Rewrite of SDFITS/GBTFITSLoad write method to allow selection and multifile output and test thereof
2) Spectrum read/write of FITS files, read/write of ESCV files, read of a variety of ASCII formats, read of GBTIDL ASCII format and tests thereof
3) Fixes issue #227 - Add primary HDU keywords to FITSload index
4) Fixing how integration numbers are created. (still one wrinkle to solve for SDFITS output)
5) Fixes issue #250 
6) Fixes issue #269 

What is still needed
- Output for Scan/ScanBlock  -- this entails essentially making and SDFITS format writer. 
- Documentation & notebooks

### CODE REVIEW

**Comment by mpound** [comment]
The failures are because astropy 6 has changed the method name from update to update_header and we are pinned at 5.3 in these tests.  Hmmm

**Comment by astrofle** [comment]
I think it would be better to have the multifits write mode append the VEGAS bank name rather than a number to the filenames.

**Comment by mpound** [comment]
Yes, it would be better.   But the code should be general, so it would have to do something like grab the last char of the existing filename stem. But that does not cover the case of a project directory with FITS files that don't share the same naming convention.   This likely will need to be handled with an additional user argument to either follow the convention of the existing filesnames or use numbers....?

**Comment by astrofle** [comment]
If you do
```Python
sdf = GBTFITSLoad(...)
sdf.write("foo.fits")
```
you get an exception about the selection resulting in zero rows.

**Comment by mpound** [comment]
> If you do
> 
> ```python
> sdf = GBTFITSLoad(...)
> sdf.write("foo.fits")
> ```
> 
> you get an exception about the selection resulting in zero rows.

Fixed in latest push

**Comment by mpound** [comment]
@astrofle The recent pushes have Scan/ScanBlock writing.

**Comment by astrofle** [comment]
will check tomorrow

**Comment by mpound** [comment]
Latest push has notebook examples.  I didn't put in a working example of multifits just noted it is possible because I did not want to force users to download multiple FITS files.

**Comment by mpound** [comment]
also fixed the conflicts with main

**Comment by astrofle** [comment]
Thanks Marc. I'll review it on Monday.

**Comment by astrofle** [comment]
This causes an error:
```Python
from dysh import util
from dysh.fits.gbtfitsload import GBTFITSLoad
f = util.get_project_testdata() / "AGBT18B_354_03/AGBT18B_354_03.raw.vegas/"
g = GBTFITSLoad(f)
g.write("merged.fits", multifile=False)
```
Error:
```Python
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[1], line 5
      3 f = util.get_project_testdata() / "AGBT18B_354_03/AGBT18B_354_03.raw.vegas/"
      4 g = GBTFITSLoad(f)
----> 5 g.write("merged.fits", multifile=False)

File /home/sandboxes/psalas/Dysh/dysh/src/dysh/fits/gbtfitsload.py:1745, in GBTFITSLoad.write(self, fileobj, multifile, verbose, output_verify, overwrite, checksum, **kwargs)
   1743         print(f"Total of {total_rows_written} rows written to files.")
   1744 else:
-> 1745     hdu = self._sdf[k]._hdu[fi[0]].copy()
   1746     outhdu = fits.HDUList(hdu)
   1747     for k in fi:

UnboundLocalError: local variable 'k' referenced before assignment
```

**Comment by mpound** [comment]
Do a pull and try it now please

**Review by astrofle — APPROVED** [review]
Great work

**Pull request merged**
