### PR TITLE
Baseline patch

### PR DESCRIPTION
**Pull request by teuben**
Here are a lot of improvements (with some caveats about units) for things related to comments on frequency switching for 0.3.0

### CODE REVIEW

**Comment by astrofle** [comment]
@mpound @teuben Was there a decision made about the baseline selection units being displayed?

**Comment by mpound** [comment]
@astrofle @teuben This is more than a displayed units issue.   It looks exclude_to_region() is not doing the conversion to SpectralRegion correctly in the case of input as channels.

**Comment by astrofle** [comment]
Shouldn't this go into `release-0.3.0` ?

**Review by astrofle — APPROVED** [review]
Looks fine, but I think this should go into `release-0.3.0` not into `main`.

**Comment by mpound** [comment]
It should go into both.

**Pull request merged**
